### ISSUE TITLE
config.js

### ISSUE THREAD

**Issue by ekonotek** [alan345/naperg#13]
Could you elaborate on exactly which settings server/src/config/config.js should contain?
Thanks in advance.

Never mind seems those are for the email service.

But when I execute docker-compose this is the error I'm getting: 

Pulling prisma (prismagraphql/prisma:1.8)...
ERROR: Get https://registry-1.docker.io/v2/prismagraphql/prisma/manifests/1.8: unauthorized: incorrect username or password

**Comment by alan345** [comment]
You have an example of config file here: https://github.com/alan345/naperg/blob/master/server/src/config/config_example.js yes it is just for emails. I don't think your issue is related. 

Have you solved it?

**Comment by ekonotek** [comment]
Thanks for the quick response Alan.
No not yet.
Don't think they are related either.
Seems related to Prisma. Like the app is trying to connect to my Prisma
account but it can't.
In all the examples I've done with Prisma they connect like "magic". I need
to look into that more.

Thanks again. I'm really exited to get your Boilerplate up and working.
Count on a sixpack of your favorite mexican beer.

**Comment by ekonotek** [comment]
It works like a champ!

Issues were related to local docker.
1) docker should be running
2) *docker login* (do not accept the defaults, and change email to username)
3) *docker-compose up -d*
4) If you get error saying port already in use. Do *docker ps -aq* and use
those values in *docker rm <val>* until *docker ps -aq* comes clean. Then
run *docker-compose up -d* again
5) continue with your instructions until app opens in localhost:3000

Hope this helps somebody else.

**Comment by alan345** [comment]
Thanks a lot for you explanation. If someone is having the same issue I will add a comment in the readme. 
@ekonotek thanks you so much for your mexican beer! I took La Lupulosa ;)
