### ISSUE TITLE
Add this project to awesome-prisma

### ISSUE THREAD

**Issue by catalinmiron** [alan345/naperg#17]
Hi @alan345,

Thanks for making this boilerplate. Would you mind if I'll add it to https://github.com/catalinmiron/awesome-prisma? 

Thanks!

**Comment by alan345** [comment]
Hi! 
Thanks for your message! Yes of course, you can add it to your page! Thanks a lot!

**Comment by catalinmiron** [comment]
Done: https://github.com/catalinmiron/awesome-prisma/pull/3.

Once again, thanks!
