### ISSUE TITLE
Subscription Error

### ISSUE THREAD

**Issue by Donskelle** [alan345/naperg#20]
Hi, i am trying to use this app as boilerplate. Everything works fine beside subscriptions.  

If i send something in chat, i get an error. React or graphql playground result in same error.
```
{
  "error": {
    "name": "TypeError",
    "message": "Cannot read property 'chat' of undefined"
  }
}
```
Server Console doesn't throw any errors.
I am using node in version 9.8 and npm in version 6.4.1 on win 10. Someone can help me?

**Comment by sen0va** [comment]
I have the same problem.

**Comment by alan345** [comment]
this issue appears when we upgrade Prisma to `1.18`. I have created an issue in Github and let you know
https://github.com/nikolasburk/subscriptions/issues/2

**Comment by alan345** [comment]
Issue has been solved by upgrading:
"graphql-yoga": "1.16.0" =>  "graphql-yoga": "1.16.4",
"prisma-binding": "2.1.4" => "prisma-binding": "2.1.6",
"prisma": "1.13.7" => "prisma": "1.18.1"

https://github.com/alan345/naperg/commit/877628ab263a04693fbd7879d4e3f89647d3c7f6#diff-d9505df4ce0441b9486ff4a0d2c4d2ec

![image](https://user-images.githubusercontent.com/15246526/47121206-aabe7980-d226-11e8-8095-c2a42cf2acdf.png)


please re-open ig you have any questions.
