### ISSUE TITLE
Too much content

### ISSUE THREAD

**Issue by comlaterra** [alan345/naperg#21]
Despite the setup is really good, this "boilerplate" contains an example of usage that can't be removed without changing half of the project.

It would be interesting to have a way to start the project as a boilerplate, so without content. 
No cars, no posts, no feeds. 

The RBA part is subject to discussion if it makes sense to be included in the boiler plate or not. I would vote for not.

Thanks for the contribution. 
Really inspiring and helpful

**Comment by comlaterra** [comment]
Ok, thanks for the explanation. Anyway, If I have some time I may submit a command to load the example-content.

Cheers

**Comment by alan345** [comment]
thanks @comlaterra!

**Comment by mbilbao** [comment]
I think @comlaterra has made a good point. Despite this boilerplate has a great features, the examples should be optional. So we can get one instance for practicing and another one as a template.
Anyway, really good job!

**Comment by anton6** [comment]
In my case the content is actually really helpful. Because I am total beginner at Graph QL it really shows how everything fits together.
