### ISSUE TITLE
Multiple File Upload (images for posts)

### ISSUE THREAD

**Issue by pisanGoreng** [alan345/naperg#23]
Hi Alan!
I would like to add a **multi file** upload for the "post" section but presently when I change the fileName to array it does not allow me to save it to graphql.  I want to display and save many photos for a single post.

I have changed nameFile to an array in "createpage.js"
`  state = {
    title: '',
    text: '',
    nameFile:[],
statusip:'',
  }`

And I have changed the fileupload to accept multiple by assigning a multiple to the input. The system can receive the files but it doesnt seem to add into the database and I am unable to retrieve it from my Feed and Draft page.
```
`class UploadFile extends React.Component {
  state = {
    isEditMode: true,
    imageURL: [],
  }`

```
the input segment for UploadFile.js
```
{this.state.isEditMode && (
            <form onSubmit={this.handleUploadImage}>
              <input
                className='f6 link dim br1 ba ph3 pv2 fr mb2 dib black'
                ref={(ref) => { this.uploadInput = ref }}
                onChange={this.handleUploadImage}
                type='file' multiple/>

            </form>
          )}
```

In the GraphQL schema and i have also changed the file to array of string.
```
`type Post {
  id: ID! @unique
  isPublished: Boolean! @default(value: "false")
  title: String!
  text: String!
  nameFile: [String!]!
  author: User
  cars: [Car!]!
}`

```

PS: Love your work.

**Comment by alan345** [comment]
Hi!
What you did looks good. What is the error you face?
did you `prisma deploy` to get schema updated?
Thanks

**Comment by pisanGoreng** [comment]
Yes, i run  prisma deploy anytime i make a change to the schema.  When I upload the files the files get added to the Media server but it doesnt get added to the database. 

When i select multiple files at the create post page.
```
OPTIONS /upload 204 0.624 ms - 0
post success
POST /upload 200 116.495 ms - 35

```

After i create the post i get:
```
GET / 404 0.742 ms - 1228
Error: No default engine was specified and no extension was provided.
    at new View (media/node_modules/express/lib/view.js:61:11)
    at Function.render (media/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (media/node_modules/express/lib/response.js:1008:7)
    at media/app.js:53:7
    at Layer.handle_error (media/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (media/node_modules/express/lib/router/index.js:315:13)
    at media/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (media/node_modules/express/lib/router/index.js:335:12)
    at next (media/node_modules/express/lib/router/index.js:275:10)
    at media/app.js:42:3
```

**Comment by alan345** [comment]
this error is not related to your issue. 

Uploading a file and saving a post (with an image) are 2 different things.

1/ you upload, the answer is the URL of image.
2/ the Url of the image is stored in a state `this.setState({nameFile: nameFile})` https://github.com/alan345/naperg/blob/4eaa0e7fb7263596944bc8a004283a42d2abcb17/react/src/components/post/CreatePage.js#L48
3/ Post is saved with function `this.handlePost` with the url of the image  `nameFile` https://github.com/alan345/naperg/blob/4eaa0e7fb7263596944bc8a004283a42d2abcb17/react/src/components/post/CreatePage.js#L50

If step1 works, step 2 should be stored in an array of image. step 3 `nameFile`  should be not a string but an array.

hope it helps

**Comment by pisanGoreng** [comment]
I believe my problem is with how i send the array of strings to the API. 
As far as errors go that's the only one I'm receiving.

I think part of my problem may be related to the this.handlePost. Chances are I'm making a mistake with the nameFile part.
```
  handlePost = async e => {
    e.preventDefault()
    const { title, text} = this.state
    let idCars = this.state.idCars
    await this.props.createPostMutation({
      variables: {
        data: {
          title,
          text,
          nameFile:[],
          cars: {
            connect: idCars
          } ,
        }
      }
    })

    this.props.history.replace('/drafts')
  }
```

**Comment by alan345** [comment]
when nameFile contains URLs, you have an error?
`nameFile:['http://example.com/image1.png', 'http://example.com/image2.png']`

**Comment by pisanGoreng** [comment]
I think the page isnt appending to the array.
`nameFile:[]`
seems to be empty

**Comment by alan345** [comment]
See my point 2/ above. you need to update state after uploading image.

**Comment by pisanGoreng** [comment]
but doesnt this already update the state?
```
<UploadFile
            isEditMode={true}
            onSelectFile={(nameFile) => {this.setState({nameFile: nameFile})}}/>
```
I'm having trouble understanding how to manipulate the state. Is there a different method for updating the state if it is an array? Cause the images are uploaded to the server.

**Comment by nicknonis** [comment]
I havent tried it personally but maybe u can try something like this?
```
this.setState({
 nameFile: [...this.state.nameFile, newelement]
})
```
Referencing [stackoverflow](https://stackoverflow.com/questions/26253351/correct-modification-of-state-arrays-in-reactjs)

**Comment by alan345** [comment]
It could be one lead, indeed. I close this issue. Reopen if you have an issue regarding this stack

**Comment by pisanGoreng** [comment]
Where should i define the newelement at?
