### ISSUE TITLE
Why mySQL and not Postgres?

### ISSUE THREAD

**Issue by anton6** [alan345/naperg#30]
Hi @alan345,

Great boilerplate, thanks for the effort and work put into the project.

Just wanted to ask why you decided to go with mySQL over posgres for this boiler plate? Any particular reason?

Thanks

**Comment by alan345** [comment]
Hello @anton6 !
Thanks for your comment. For 2 reasons:
-When I started this project, only mySql was enabled with this Prisma.
-Market share are higher for MySqL
![image](https://user-images.githubusercontent.com/15246526/56671644-df920a00-6669-11e9-9ed6-121734ce29ef.png)
https://www.datanyze.com/market-share/databases

That being said, I think now, with Prisma, you can easily change it to postgres
Thanks

**Comment by anton6** [comment]
Thanks for the explanation

**Comment by anton6** [comment]
Switched to Postgres no problem as per your reply. Thanks
