### ISSUE TITLE
Do you achieve Protected Endpoint / Resolvers ?

### ISSUE THREAD

**Issue by AlbertKant** [alan345/naperg#32]
Thank you for the great job you have done, and it is a brilliant project.

Just a question, I did not see Protected Endpoint / Resolvers mechanism in your project,

except the 
```
const userId = getUserId(ctx)
... check userId here ...
```
So have you considered to achieve the Protected Endpoint / Resolvers ?

**Comment by anton6** [comment]
Also curious regarding this question. Thanks

**Comment by alan345** [comment]
It is a very good question I have been struggling with! 
Here the question: https://stackoverflow.com/questions/52527934/graphql-security-protect-nested-data
I have solved this question on another project with directives. https://www.google.com/amp/s/www.prisma.io/blog/graphql-directive-permissions-authorization-made-easy-54c076b5368e/amp/

Good luck!
