### ISSUE TITLE
Dark background for the technologies used image

### ISSUE THREAD

**Issue by gauravgupta98** [alan345/naperg#34]
NICE TO HAVE SUGGESTION
Can we have a dark background for the technologies used image as it doesn't look good in dark mode (checkout the below image).

![image](https://user-images.githubusercontent.com/31717079/107874066-e80da180-6edc-11eb-9722-13c848974771.png)

**Comment by alan345** [comment]
Hello! You are definitely right. Thanks for the alert.
Do you have photoshop skills? I am not very good at design stuffs..

**Comment by gauravgupta98** [comment]
Hi @alan345 
I can have a look at this. Please assign it to me. Thanks

**Comment by alan345** [comment]
Thanks! Any other suggestion to make the repo nicer? and easier to understand?

**Comment by gauravgupta98** [comment]
@alan345 I'll go through the code once after fixing this and let you know as I've checked the code yet. Thanks

**Comment by gauravgupta98** [comment]
@alan345 Also, checkout my whatsapp clone repo and let me know your thoughts mate. Give a star if you like it ;)

**Comment by alan345** [comment]
Nice! I Added a star. Why not using typescript?

**Comment by gauravgupta98** [comment]
Thanks. Actually I'm learning typescript now and using it in a different repo - twitter clone (still under development). Thanks for the suggestion. If you want to contribute and shift the codebase of that repo to TS, then most welcome ;)

**Comment by gauravgupta98** [comment]
![image](https://user-images.githubusercontent.com/31717079/109178534-f5fdd500-77ae-11eb-8420-d2f9cfbb7334.png)
Check it out

**Comment by gauravgupta98** [comment]
![105572650-5364b900-5d0d-11eb-8f21-0c3006e29d14](https://user-images.githubusercontent.com/31717079/109178895-59880280-77af-11eb-961e-bd5187670f2e.png)

**Comment by alan345** [comment]
Thanks. But now it is not working for white background..

**Comment by alan345** [comment]
I created an image with transparency
![naperg](https://user-images.githubusercontent.com/15246526/109192820-92db5680-774c-11eb-9480-d3a6883b8588.png)

[Archive.zip](https://github.com/alan345/naperg/files/6044785/Archive.zip)
