### ISSUE TITLE
Uniqid is not secure for random tokens

### ISSUE THREAD

**Issue by geekuillaume** [alan345/naperg#6]
As the uniqid documentation explains ([here](https://www.npmjs.com/package/uniqid)), it is generating a token by concatenating the time, mac address and process id. It is quite easy to get the process id and mac address and then generate token. Uniqid should be replace by a cryptographic strong random string generator: https://stackoverflow.com/questions/8855687/secure-random-token-in-node-js to replace uniqid here: https://github.com/alan345/naperg/blob/315d6f53053b83afd6594588db4e47635c359a76/server/src/resolvers/auth.js#L25

**Comment by alan345** [comment]
Thanks for the warning! I have changed it to `crypto.randomBytes()`. ([link](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback))

https://github.com/alan345/naperg/commit/06589130f8f08c876d027d52fbe1a5b1251c9753
