### ISSUE TITLE
Why separate express server?

### ISSUE THREAD

**Issue by sakhmedbayev** [alan345/naperg#8]
First of all, let me thank you for the great job you have done! I was looking for this kind of solution for a while.

I am still learning Prisma, so my question can be irrelevant. I wonder why your stack is using a separate `express` server. I see that `server` package/ folder already includes `graphql-yoga` which is basically `express`. Was the purpose of this to completely decouple server side from prisma? Where can I learn more about it?

**Comment by alan345** [comment]
Hello! Thanks for your message! You are definitely Right! You can use graphql yoga for your API. I just did it for having his own image/media server. 

I started to use express in graphql-yoga here:

**Comment by sakhmedbayev** [comment]
Thanks for the quick response @alan345! I am trying to understand how image uploading works in the boilerplate. How do you associate an image file with a user? How do you then retrieve a proper file?

**Comment by alan345** [comment]
the component UploadFile (https://github.com/alan345/naperg/blob/master/react/src/components/user/UserPage.js#L125) update state 'nameFile'. 
and function updateUser() https://github.com/alan345/naperg/blob/master/react/src/components/user/UserPage.js#L180 trigger mutation UPDATE_USER_MUTATION. Hope it helps

**Comment by atymchuk** [comment]
I pretty much had the same concern. 

@alan345  Did I get you right: it's currently not possible to implement the file upload using `graphql-yoga` alone?

**Comment by alan345** [comment]
Yes it is possible to use graphql-yoga alone. 
I wanted to have a separate media server
