### ISSUE TITLE
Roles based permissions on the front end

### ISSUE THREAD

**Issue by sakhmedbayev** [alan345/naperg#9]
Question: does this boilerplate implement roles based permission on the front end? If so, where?

**Comment by alan345** [comment]
In the front end it is on this screen:
https://camo.githubusercontent.com/7914c7a97bb6b06ec2afeea014d390cb36a77553/68747470733a2f2f6a2e676966732e636f6d2f41506c3631312e676966
In file user.js

**Comment by sakhmedbayev** [comment]
So basically, on the front end, there are no roles based permissions at the moment? Correct?

**Comment by alan345** [comment]
Yep, Just roles. No permissions.

**Comment by sakhmedbayev** [comment]
Any plans to add that functionality?

**Comment by alan345** [comment]
Can you give me more details about what you think with a specific example?

**Comment by sakhmedbayev** [comment]
For an instant, only admins can change users' role or only admins can edit all cars, users can edit only their own cars...

**Comment by alan345** [comment]
Here you have an example:

FrontEnd: https://github.com/alan345/naperg/blob/master/react/src/components/car/DetailCar.js#L47
Check if user has right to call button DELETE.

Don't forget to check if user is ADMIN in the backend also.
https://github.com/alan345/naperg/blob/master/server/src/resolvers/Mutation.js#L46

Hope it helps
